smc-tools: Fix function declaration to use a void prototype
After the below commit, the argument in gen_nl_open(pname) is not used
anymore. They missed removing it as part of this commit itself.

In Fedora 42, they are using GCC version 15.x, which uses C23 standard by
default[1]. Since C23, function declarations without prototypes are considered
to be invalid[2]. That's why we got the following compiler error in Fedora 42,
not in the older versions of Fedora, where c23 are not yet used as the standard.

DEBUG: smc.c: In function 'main':
DEBUG: smc.c:147:13: error: too many arguments to function 'gen_nl_open';
DEBUG:  147 |        if (gen_nl_open(myname))
DEBUG:      |            ^~~~~~~~~~~ ~~~~~~
DEBUG: In file included from smc.c:27:
DEBUG: libnetlink.h:63:5: note: declared here
DEBUG:   63 | int gen_nl_open();
DEBUG:      |    ^~~~~~~~~~~
DEBUG: make: *** [Makefile:110: smcd.o] Error 1
DEBUG: make: *** Waiting for unfinished jobs....

Thus, we need to explicitly mention *void* if we intend to pass no argument in our case.

[1] https://gcc.gnu.org/gcc-15/changes.html
[2] https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2841.htm

Fixes: b491096 ("libnetlink: use the leading string "Error:" in all nl error strings")

Reviewed-by: Wenjia Zhang <wenjia@linux.ibm.com>
Signed-off-by: Mahanta Jambigi <mjambigi@linux.ibm.com>